language: bash
services: docker

env:
  - VERSION=3.6 VARIANT=stretch
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
before_script:
  - env | sort
  # go inside the correct build file
  - FOLDER="$PWD/bot"
  - cd "python$VERSION/$VARIANT"
  - slash='/'; image="luckydonald${slash}telegram-bot:python${VERSION}-${VARIANT//$slash/-}"
script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build --build-arg FOLDER=$FOLDER -t "$image" .
      ~/official-images/test/run.sh "$image"
      # travis_retry docker push "$image"
      if [ -d onbuild ]; then
        onbuildFrom="$(awk 'toupper($1) == "FROM" { print $2; exit }' onbuild/Dockerfile)"
        docker tag "$image" "$onbuildFrom"
        docker build --build-arg FOLDER=$FOLDER -t "$image-onbuild" onbuild
        ~/official-images/test/run.sh "$image-onbuild"
        # travis_retry docker push "$image-onbuild"
      fi
    )
after_script:
  - docker images
